export const SET_PHONES = 'SET_PHONES'

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'

export const SET_MIN_PRICE = 'SET_MIN_PRICE'

export const SET_MAX_PRICE = 'SET_MAX_PRICE'

export const SET_TOTAL_MIN_PRICE = 'SET_TOTAL_MIN_PRICE'

export const SET_TOTAL_MAX_PRICE = 'SET_TOTAL_MAX_PRICE'

export const SET_STORAGE_SIZES = 'SET_STORAGE_SIZES'

export const SET_ALL_STORAGE_SIZES = 'SET_ALL_STORAGE_SIZES'

export const SET_TOTAL_RESULTS = 'SET_TOTAL_RESULTS'

export const SET_TOTAL_REQUESTS = 'SET_TOTAL_REQUESTS'
